pipeline{
 agent any

 environment {
    VAULT = tool name: 'vault'
    VAULT_SECRET = credentials('vault-credential')
}
stages {

    stage('Run Encrypt full file') {

        steps {
            sh "cd tests && ${vault} -k ${vault_secret} encrypt full.txt full.enc.txt"
            sh "cat tests/full.enc.txt"
        }
    }
    stage('Run Decrypt') {

        steps {
            sh "cd tests && ${vault} -k ${vault_secret} decrypt full.enc.txt full.dec.txt"
            sh "cmp -s tests/full.dec.txt tests/full.txt"
            sh "cat tests/full.dec.txt"
        }
    }

    stage('Run Encrypt Vars only') {

        steps {
            sh "cd tests && ${vault} -k ${vault_secret} -e MADE -e AUTHOR -e URL -e COMPANY encrypt vars.txt vars.enc.txt"
            sh "cat tests/vars.enc.txt"
        }
    }

    stage('Run Decrypt Vars only') {

        steps {
            sh "cd tests && ${vault} -k ${vault_secret} -e MADE -e AUTHOR -e URL -e COMPANY decrypt vars.enc.txt vars.dec.txt"
            sh "cmp -s tests/vars.dec.txt tests/vars.txt"
            sh "cat tests/vars.dec.txt"
        }

    }
    }
}